import { createClient } from '@supabase/supabase-js';

// Supabase credentials from user input
// Use process.env as configured in vite.config.ts to avoid Netlify secrets scanner
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Supabase environment variables SUPABASE_URL and SUPABASE_ANON_KEY must be set.');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'X-Client-Info': 'kunajoto-web',
    },
  },
});

// Define the database schema types for better type safety in the application
// This is a simplified version, the full types would be generated by Supabase CLI
export type Database = {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          username: string | null;
          full_name: string | null;
          avatar_url: string | null;
          role: string;
          preferences: any | null;
          onboarding_completed: boolean;
          preferences_completed: boolean;
          created_at: string;
        };
        Insert: {};
        Update: {};
      };
      venues: {
        Row: {
          id: string;
          name: string;
          type: string | null;
          image_url: string | null;
          latitude: number | null;
          longitude: number | null;
          vibe_score: number | null;
          vibe_confidence: string | null;
          vibe_trend: string | null;
          district: string | null;
          description: string | null;
          price_level: number | null;
          is_promoted: boolean;
          created_at: string;
        };
        Insert: {};
        Update: {};
      };
      user_favorites: {
        Row: {
          user_id: string;
          venue_id: string;
          created_at: string;
        };
        Insert: {};
        Update: {};
      };
      reviews: {
        Row: {
          id: string;
          user_id: string;
          venue_id: string;
          rating: number;
          text: string | null;
          created_at: string;
        };
        Insert: {};
        Update: {};
      };
      app_data: {
        Row: {
          key: string;
          data: any;
          updated_at: string;
        };
        Insert: {};
        Update: {};
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};

// Helper function to handle sign-in/sign-up
export const handleAuth = async (type: 'signin' | 'signup', email: string, password: string, rememberMe: boolean = true) => {
  if (type === 'signup') {
    const { data, error } = await supabase.auth.signUp({
      email,
      password,
    });
    if (error) throw error;
    return data;
  } else {
    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password,
      options: {
        redirectTo: rememberMe ? undefined : window.location.origin, // Supabase handles session persistence, but we can use this for a cleaner flow
      }
    });
    if (error) throw error;
    return data;
  }
};

// Helper function to get the current user session
export const getSession = async () => {
  const { data: { session } } = await supabase.auth.getSession();
  return session;
};

// Helper function to sign out
export const signOut = async () => {
  const { error } = await supabase.auth.signOut();
  if (error) throw error;
};

// Helper function to fetch user profile
export const fetchUserProfile = async (userId: string) => {
  const { data, error } = await supabase
    .from('user_profiles')
    .select('*')
    .eq('id', userId)
    .single();
  if (error) throw error;
  return data;
};

// Helper function to update user profile
export const updateUserProfile = async (userId: string, updates: Partial<Database['public']['Tables']['user_profiles']['Row']>) => {
  const { data, error } = await supabase
    .from('user_profiles')
    .update(updates)
    .eq('id', userId)
    .select()
    .single();
  if (error) throw error;
  return data;
};
